# Generated by Django 3.2.8 on 2023-09-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_libro', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('descripcion', models.CharField(max_length=100, null=True, verbose_name='Descripcion del Libro')),
            ],
            options={
                'verbose_name': 'ModelLibro',
                'verbose_name_plural': 'ModelLibros',
                'db_table': 'libros',
                'managed': True,
            },
        ),
    ]
