# Generated by Django 3.2.8 on 2023-09-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='nombre_libro',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre de Libro'),
        ),
    ]
