# Generated by Django 3.2.8 on 2023-09-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_libros_nombre_libro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
