# Generated by Django 3.2.8 on 2023-09-30 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_alter_libros_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='libros',
            new_name='Modelo_libros',
        ),
    ]
