# Generated by Django 3.2.8 on 2023-09-30 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_rename_libros_modelo_libros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelo_libros',
            options={},
        ),
    ]
