# Generated by Django 3.2.8 on 2023-09-30 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_alter_modelo_libros_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='modelo_libros',
            table=None,
        ),
    ]
