# Generated by Django 3.2.8 on 2023-09-30 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0006_alter_modelo_libros_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='modelo_libros',
            table='tb_libros',
        ),
    ]
